[package]
name = 'OpenMove'
version = '0.0.1'
upgrade_policy = 'compatible'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'

[dependencies.AptosStdlib]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-stdlib'

[addresses]
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"
openmove = "0x1"